repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        include: ^(src/|tests/)
        exclude: ".*/migrations/.*"
