"""Add User.is_superuser row

Revision ID: 5339059f0ca2
Revises: 8d6ba893f481
Create Date: 2024-03-20 10:21:07.905455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5339059f0ca2'
down_revision = '8d6ba893f481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_superuser')

    # ### end Alembic commands ###
