"""empty message

Revision ID: 54b7f123f251
Revises: ea228b14ed92
Create Date: 2024-03-18 05:35:30.821721

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '54b7f123f251'
down_revision = 'ea228b14ed92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
