"""Update cascade delete relationship

Revision ID: a1df335b0734
Revises: 535d254c3666
Create Date: 2024-03-19 08:13:39.950957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1df335b0734'
down_revision = '535d254c3666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iam_auth_token', schema=None) as batch_op:
        batch_op.drop_constraint('iam_auth_token_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iam_auth_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('iam_auth_token_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
