"""empty message

Revision ID: ea228b14ed92
Revises: 374fbada0ebf
Create Date: 2024-03-16 11:06:06.091636

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea228b14ed92'
down_revision = '374fbada0ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iam_auth_token', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iam_auth_token', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
