services:
  iam-service:
    build:
      context: ${FIM_PROJECT_PATH}
      dockerfile: .docker/iam-service/Dockerfile
    volumes:
      - ${FIM_IAM_SERVICE_VOLUME_PATH}:/code
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - fim-mongo
    restart: always

  inventory-service:
    build:
      context: ${FIM_PROJECT_PATH}
      dockerfile: .docker/inventory-service/Dockerfile
    volumes:
      - ${FIM_INVENTORY_SERVICE_VOLUME_PATH}:/code
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - ELASTICSEARCH_HEALTH_ENDPOINT=${ELASTICSEARCH_HEALTH_ENDPOINT}
    depends_on:
      - fim-mongo
      - fim-redis
      - fim-elasticsearch
    restart: always

  fim-mongo:
    container_name: fim-mongo
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ${FIM_MONGO_VOLUME_PATH}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    restart: always

  fim-redis:
    container_name: fim-redis
    image: redis:latest
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
    volumes:
      - ${FIM_REDIS_VOLUME_PATH}:/data
    command:
      - redis-server
    restart: always

  fim-inventory-rq-worker:
    container_name: fim-inventory-rq-worker
    build:
      context: ${FIM_PROJECT_PATH}
      dockerfile: .docker/inventory-service/Dockerfile
    volumes:
      - ${FIM_INVENTORY_SERVICE_PATH}:/code
    depends_on:
      - fim-redis
      - inventory-service
    restart: always

  fim-elasticsearch:
    container_name: fim-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - ${ELASTICSEARCH_API_PORT}:${ELASTICSEARCH_API_PORT}
    volumes:
      - ${FIM_ELASTICSEARCH_VOLUME_PATH}:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "${ELASTICSEARCH_HEALTH_ENDPOINT}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  fim-nginx:
    container_name: fim-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - iam-service
      - inventory-service
    restart: always

volumes:
  fim-mongo:
  fim-redis:
  fim-elasticsearch:
