version: "3.7"

services:
  app:
    container_name: cpsc-449-1-app
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ../:/code
    environment:
      - FLASK_ENV=development
    depends_on:
      - cpsc-449-1-mysql
    # Leave the container running
    # command: tail -f /dev/null
    command: poetry run python app.py

  cpsc-449-1-mysql:
    container_name: cpsc-449-1-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./cpsc-449-1-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=cpsc_449_1_dev
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    command: "--default-authentication-plugin=mysql_native_password"

volumes:
  cpsc-449-1-mysql:
