services:
  iam-service:
    container_name: iam-service
    build:
      # Don't think we need the entire project?
      context: ${FIM_PROJECT_PATH}
      dockerfile: .docker/iam-service/Dockerfile
    ports:
      - ${FLASK_IAM_SERVICE_PORT_EXTERNAL}:${FLASK_PORT}
    volumes:
      - ${FIM_IAM_SERVICE_VOLUME_PATH}:/code
    depends_on:
      - fim-mongo
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    # Leave the container running
    command: tail -f /dev/null

  inventory-service:
    container_name: inventory-service
    build:
      # Don't think we need the entire project?
      context: ${FIM_PROJECT_PATH}
      dockerfile: .docker/inventory-service/Dockerfile
    ports:
      - ${FLASK_INVENTORY_SERVICE_PORT_EXTERNAL}:${FLASK_PORT}
    volumes:
      - ${FIM_INVENTORY_SERVICE_VOLUME_PATH}:/code
    depends_on:
      - fim-mongo
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    # Leave the container running
    command: tail -f /dev/null

  fim-mongo:
    container_name: fim-mongo
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ${FIM_MONGO_VOLUME_PATH}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}

volumes:
  fim-mongo:
